### ISSUE TITLE
Error when running chapter4

### ISSUE THREAD

**Issue by Geo-W** [maxwellflitton/async-rust-oreilly#1]
Hi Maxwell,

Thank you for your effort in writing this book. It has been an invaluable resource for my studies.
However, I encountered some issues while following the instructions and running the code in Chapter 4.

#### Building an Executor for Hyper:
Error: there is no reactor running, must be called from the context of Tokio 1.x runtime.
#### Listening to Sockets with Mio:
Error: Error reading from stream: A non-blocking socket operation could not be completed immediately. (os error 10035)
Outcome: That's so dingo!

## Full error for the first one:
```cmd
thread '<unnamed>' panicked at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.0\src\time\interval.rs:139:26:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: core::panicking::panic_display<tokio::runtime::handle::TryCurrentError>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\panicking.rs:197
   3: tokio::runtime::scheduler::impl$3::current::panic_cold_display<tokio::runtime::handle::TryCurrentError>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\panic.rs:99
   4: enum2$<tokio::runtime::scheduler::Handle>::current
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.0\src\runtime\scheduler\mod.rs:106
   5: tokio::time::sleep::Sleep::new_timeout
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.0\src\time\sleep.rs:257
   6: tokio::time::sleep::sleep_until
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.0\src\time\sleep.rs:63
   7: tokio::time::interval::internal_interval_at
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.0\src\time\interval.rs:139
   8: tokio::time::interval::interval
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\tokio-1.38.0\src\time\interval.rs:76
   9: hyper::client::pool::PoolInner<hyper::client::client::PoolClient<hyper::body::body::Body> >::spawn_idle_interval<hyper::client::client::PoolClient<hyper::body::body::Body> >
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.29\src\client\pool.rs:424
  10: hyper::client::pool::PoolInner<hyper::client::client::PoolClient<hyper::body::body::Body> >::put<hyper::client::client::PoolClient<hyper::body::body::Body> >
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.29\src\client\pool.rs:389
  11: hyper::client::pool::impl$11::drop<hyper::client::client::PoolClient<hyper::body::body::Body> >
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.29\src\client\pool.rs:541
  12: core::ptr::drop_in_place<hyper::client::pool::Pooled<hyper::client::client::PoolClient<hyper::body::body::Body> > >
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\ptr\mod.rs:515
  13: core::mem::drop<hyper::client::pool::Pooled<hyper::client::client::PoolClient<hyper::body::body::Body> > >
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\mem\mod.rs:992
  14: hyper::client::client::impl$3::send_request::async_fn$0<building_out_own_async_runtime::CustomConnector,hyper::body::body::Body>
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.29\src\client\client.rs:331
  15: hyper::client::client::impl$3::retryably_send_request::async_fn$0<building_out_own_async_runtime::CustomConnector,hyper::body::body::Body>
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.29\src\client\client.rs:209
  16: hyper::client::client::impl$10::poll
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\hyper-0.14.29\src\client\client.rs:633
  17: building_out_own_async_runtime::fetch::async_fn$0
             at .\src\main.rs:152
  18: building_out_own_async_runtime::main::async_block$0
             at .\src\main.rs:162
  19: async_task::raw::RawTask<enum2$<building_out_own_async_runtime::main::async_block_env$0>,tuple$<>,void (*)(async_task::runnable::Runnable<tuple$<> >),tuple$<> >::run<enum2$<building_out_own_async_runtime::main::async_block_env$0>,tuple$<>,void (*)(async_t
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.1\src\raw.rs:557
  20: async_task::runnable::Runnable<tuple$<> >::run<tuple$<> >
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.1\src\runnable.rs:781
  21: building_out_own_async_runtime::runtime::spawn_task_function::HIGH_QUEUE::closure$0::closure$0::closure$0
             at .\src\runtime.rs:41
  22: std::panicking::try::do_call<building_out_own_async_runtime::runtime::spawn_task_function::HIGH_QUEUE::closure$0::closure$0::closure_env$0,bool>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\panicking.rs:552
  23: std::panicking::try::do_catch<core::panic::unwind_safe::AssertUnwindSafe<tokio::runtime::task::harness::poll_future::closure_env$0<futures_util::future::future::Map<futures_util::future::try_future::MapErr<hyper::common::lazy::Lazy<hyper::client::client::
  24: std::panicking::try<bool,building_out_own_async_runtime::runtime::spawn_task_function::HIGH_QUEUE::closure$0::closure$0::closure_env$0>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\panicking.rs:516
  25: std::panic::catch_unwind<building_out_own_async_runtime::runtime::spawn_task_function::HIGH_QUEUE::closure$0::closure$0::closure_env$0,bool>
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\panic.rs:146
  26: building_out_own_async_runtime::runtime::spawn_task_function::HIGH_QUEUE::closure$0::closure$0
             at .\src\runtime.rs:41
  27: core::hint::black_box
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\hint.rs:337
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.1\src\task.rs:452:45:
Task polled after completion
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\std\src\panicking.rs:645
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:72
   2: core::panicking::panic_display<ref$<str$> >
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:197
   3: core::panicking::panic_str
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\panicking.rs:172
   4: core::option::expect_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library\core\src\option.rs:1995
   5: enum2$<core::option::Option<tuple$<> > >::expect<tuple$<> >
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\option.rs:896
   6: async_task::task::impl$7::poll<tuple$<>,tuple$<> >
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\async-task-4.7.1\src\task.rs:452
   7: futures_lite::future::block_on::closure$0<tuple$<>,async_task::task::Task<tuple$<>,tuple$<> > >
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:89
   8: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::try_with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure_env$0<tuple$<>,async_task::task::T
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\thread\local.rs:284
   9: std::thread::local::LocalKey<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> > >::with<core::cell::RefCell<tuple$<parking::Parker,core::task::wake::Waker> >,futures_lite::future::block_on::closure_env$0<tuple$<>,async_task::task::Task<
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\std\src\thread\local.rs:260
  10: futures_lite::future::block_on<tuple$<>,async_task::task::Task<tuple$<>,tuple$<> > >
             at C:\Users\geo\.cargo\registry\src\index.crates.io-6f17d22bba15001f\futures-lite-1.13.0\src\future.rs:79
  11: building_out_own_async_runtime::main
             at .\src\main.rs:170
  12: core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\ops\function.rs:250
  13: core::hint::black_box
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6\library\core\src\hint.rs:337
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Thank you for your time and assistance.

**Comment by maxwellflitton** [comment]
Hey @Geo-W sorry for the late reply, I have done a lot of refactoring for the final quality control, is it running now? If not can you show me the exact directory that is not working in the github repo?

**Comment by maxwellflitton** [comment]
Closing due to inactivity
